### PR TITLE
RIFEX-272/Add-channel-button

### PR DESCRIPTION
**Pull request by rorolopetegui**
This PR changes the color of the add button of a channel

image

### CODE REVIEW

**Review by mauricioirace — APPROVED** [review]
lgtm

**Comment by marcosmartinez7** [comment]
The button must be exactly like the "add subdomain" button, is the image outdated? Font size and color are different

**Review by JONAF2103 — COMMENTED** [review]
Why we don't use the same class that the other add buttons have? i mean Fede already created that for the other add buttons right? It looks different from the other adds

**Comment by rorolopetegui** [comment]
> Why we don't use the same class that the other add buttons have? i mean Fede already created that for the other add buttons right? It looks different from the other adds
There i changed to use the same class as the add subdomain button

**Review by JONAF2103 — APPROVED** [review]
LGTM

**Pull request merged**
