### PR TITLE
RIFEX-136/Callback-CloseChannel

### PR DESCRIPTION
**Pull request by rorolopetegui**
This PR adds the callback for when a close channel is done, and you're in the channel detail. It disables the actions for open channel, and changes the state of components.
Also a var name is fixed to get subscribed to notifier.

### CODE REVIEW

**Review by marcosmartinez7 — COMMENTED** [review]
Why we navigate back? to close the modal?

**Review by JONAF2103 — APPROVED** [review]
LGTM

**Review by JONAF2103 — APPROVED** [review]
LGTM

**Review by debrayperalta — APPROVED** [review]
lgtm

**Pull request merged**
