### PR TITLE
RIFEX-256/sort-networks

### PR DESCRIPTION
**Pull request by mauricioirace**
Set RSK Main Net as default network
rsk as default channel

### CODE REVIEW

**Review by rorolopetegui — COMMENTED** [review]
Can we add a image so, we can see how its showed now?

**Review by JONAF2103 — APPROVED** [review]
LGTM let's make sure that the behaviour is the correct by testing it when the plugin is removed from the browser and added again, the idea is to have RSK by default

**Comment by mauricioirace** [comment]
> Can we add a image so, we can see how its showed now?

Yes, I've just uploaded a screenshot

**Review by rorolopetegui — APPROVED** [review]
lgtm

**Pull request merged**
